version: "3.5"

services:
  app-server:
    container_name: app-webserver
    build:
      context: .docker/server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .docker/server/logs/:/var/log/nginx/
      - ./src/:/var/www:cached
    links:
      - app-php
    env_file: .env
    tty: false

  app-php:
    container_name: app-php
    build:
      context: .docker/php
      dockerfile: Dockerfile
      args:
        - "UID=1000"
        - "GID=1000"
    ports:
      - "9000:9000"
    volumes:
      - ./src/:/var/www:cached
    env_file: .env
    restart: always
    tty: false  
    links:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: app-phpmyadmin
    ports:
      - 3390:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db
  db:
    image: mysql:5.7
    container_name: app-db
    ports:
      - "3307:3306"
    volumes:
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=mydatabase